name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # ou la branche de ton choix

permissions:
  contents: write  # Assure-toi que GitHub Actions peut écrire

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install  # Utilisation de npm au lieu de pnpm

      - name: Build the project
        run: npm run build  # Assure-toi que ton script de build existe

      - name: Deploy to GitHub Pages
        run: npm run deploy  # Assure-toi que ton script de déploiement existe
